name: Ruby

run-name: ${{ github.actor }} is running this workflow

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'
        database:
          - mysql
          - sqlite3

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    -
      name: Set Bundle
      run: |
        gem update --system
        gem install bundler
    -
      name: Bundle Install
      run: |
        DATABASE=${{ matrix.database }} bundle install --jobs 4 --retry 3
        bundle lock --add-platform x86_64-linux
        bundle update

    - name: Run the default task
      run: DATABASE=${{ matrix.database }} bundle exec rake
